### ISSUE TITLE
Support for the hierarchical rule is missing

### ISSUE THREAD

**Issue by chrisgorgo** [bids-apps/SPM#11]
```
Execution failed: /opt/spm12/spm_BIDS_App.m
Error using fileread (line 22)
Could not open file /snapshot/data/sub-001/fmap/sub-001_dir-AP_epi.json. No such file or directory.
Error in fileread (line 22)
Error in parse_subject (line 326)
Error in spm_BIDS (line 122)
Error in spm (line 1210)
Error in spm_standalone (line 115)
```

The correct JSON file was in `/snapshot/data/dir-AP_epi.json`

More info at https://openneuro.org/datasets/ds001105/versions/00001?app=SPM&version=17&job=5a298a27fce2fd0001047fb6

**Comment by gllmflndn** [comment]
Thanks for the report. I fixed the bug in the SPM12 repository and will rebuild the Docker container shortly. When this is done, is there a way to restart the SPM analysis on OpenNeuro?

PS: On the OpenNeuro page, there is a link to OSF in the "References and Links":
  https://osf.io/x32te/
and from there a link back to OpenNeuro:
  https://openneuro.org/datasets/ds001105
but you get "You are not authorized to view this dataset" as only this one works:
  https://openneuro.org/datasets/ds001105/versions/00001

**Comment by chrisgorgo** [comment]
Thanks for fixing this! If you publish a new version of SPM App on GitHub I will be able to deploy it on OpenNeuro and we will be able to submit a new job.

**Comment by gllmflndn** [comment]
[v0.0.10](https://hub.docker.com/r/bids/spm/tags/) has landed. Thanks!

**Comment by chrisgorgo** [comment]
I'm ready for deployment, but I need a text description of the '--config'
input argument. Thoughts?

Best,
Chris

**Comment by chrisgorgo** [comment]
Also - should I enable group level?

**Comment by gllmflndn** [comment]
I have added an example of a task at the group level (computing a mean structural image) so you can enable it.

The '--config' input argument allows to specify the path to a MATLAB script that contains a description of the task to perform at the participant or group level. See examples with the configuration files ```pipeline_participant.m``` and ```pipeline_group.m``` that are used by default, when the '--config' argument is not specified.

**Comment by chrisgorgo** [comment]
Thanks!

Does the app require a different config file for `participant` and `group`
stages?

On OpenNeuro we pass the same inputs (including config files) to all
stages. Also user does not have influence on which stages are run (for
example for SPM we will always run `participant` stage followed by `group`
stage). Does this align with the current design of SPM App?

Best,
Chris

**Comment by gllmflndn** [comment]
Yes, the way I thought about it is to have a different configuration file per level of analysis - it kind of makes sense given that analyses are always different. That said, a single user-specified configuration file could be written like this:
```
if strcmp(BIDS_App.level,'participant')
    % first level analysis
else
    % second level analysis
end
```
so this is not a limitation for OpenNeuro. 
I could also add the option for '--config' to point to a folder (instead of a single file) that would contain configuration files for each level of analysis, and would be picked up appropriately automatically by the App.

**Comment by chrisgorgo** [comment]
Uploading folders via a browser is a bit tricky so the solution with a
single file and if statements would work better. Could you update the
example so I could point to it in the app description on OpenNeuro? Thanks!

Best,
Chris

**Comment by gllmflndn** [comment]
I have added a paragraph about the configuration file in the README:
https://github.com/BIDS-Apps/SPM#configuration-file

**Comment by chrisgorgo** [comment]
Thanks! I updated openneuro. You can take it for a spin if you want!

Best,
Chris

**Comment by gllmflndn** [comment]
Will do, thanks!
