### ISSUE TITLE
spm8 equivalent?

### ISSUE THREAD

**Issue by vsoch** [bids-apps/SPM#12]
hey BIDS maintainers!

I'm working on an older (spm8) pipeline and wondering if there was a container (or just the binary that is installed inside) for spm8? If not, can we make one, can I make one?

Many thanks!

**Comment by chrisgorgo** [comment]
I don't think there is BIDS support in SPM8, but there should be a compiled version of SPM8. @gllmflndn would have to provide a link for it though.

**Comment by vsoch** [comment]
Yes this would be exactly what is needed! I found another version at https://github.com/spm/spm-docker, also maintained by @gllmflndn ... oh wait I think I found something under the "utopia" folder... http://www.fil.ion.ucl.ac.uk/spm/download/restricted/utopia/spm8/ okay, we're good :)
