### ISSUE TITLE
Increasing the log verbosity

### ISSUE THREAD

**Issue by chrisgorgo** [bids-apps/SPM#9]
I'm trying to run SPM on a dataset I unfortunately cannot share and I am getting the following error:

```
SPM12, version 7048 (standalone)
  MATLAB, version 9.2.0.538062 (R2017a)
   ___  ____  __  __                                            
  / __)(  _ \(  \/  )                                           
  \__ \ )___/ )    (   Statistical Parametric Mapping           
  (___/(__)  (_/\/\_)  SPM12 - http://www.fil.ion.ucl.ac.uk/spm/
  
  Execution failed: /opt/spm12/spm_BIDS_App.m
  Error using spm_BIDS (line 56)
  BIDS dataset description could not be read.
  Error in spm_BIDS (line 56)
  Error in spm (line 1206)
  Error in spm_standalone (line 115)
```

Would there be a way to increase verbosity of the logs?

**Comment by gllmflndn** [comment]
The error you get means that there was an issue with the `dataset_description.json` file: either the JSON parsing failed or one (or both) of the mandatory fields `BIDSVersion` or `Name` was missing.
If it does not help, could you at least share the `dataset_description.json` file?

I'm also going to update the app to a more recent version of SPM12 dev.
